services:
  - type: web
    name: arcperp-price-server
    runtime: node
    rootDir: backend
    buildCommand: npm install --include=dev
    startCommand: npm run price-server
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PYTH_HERMES_URL
        value: https://hermes.pyth.network

  - type: web
    name: arcperp-order-server
    runtime: node
    rootDir: backend
    buildCommand: npm install --include=dev
    startCommand: npm run order-server
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: ARC_RPC_URL
        sync: false
      - key: BOT_PRIVATE_KEY
        sync: false
      - key: PERP_ENGINE_ADDRESS
        sync: false
      - key: PRICE_SERVER_WS_URL
        sync: false
